name: AFL

on:
  push:
    branches: [ master ]
    
  pull_request:
    branches: [ master ]
       

permissions:
  contents: read



jobs:
  build:

    runs-on: ubuntu-latest    
     
    steps:
    - uses: actions/checkout@v3
    
    - name: Build and push docker image
      uses: mr-smithers-excellent/docker-build-push@v4
      with:
        image: khushi2/oss-fuzz
        registry: docker.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        
  AFL-Fuzzer:
    runs-on: ubuntu-latest
    env: 
      AFL_I_DONT_CARE_ABOUT_MISSING_CRASHES: 1
    
    steps:
      - uses: actions/checkout@v3
      - name: Compilation
        run: |
          make
          cd llvm_mode
          sudo apt-get install -y clang llvm-dev
          set $LLVM_CONFIG=llvm-config-3.5
          sudo make
          cd ..
          sudo make install
          
        
      - name: AFL Build
        id: build
        uses: google/oss-fuzz/infra/cifuzz/actions/build_fuzzers@master
        with: 
          language: c
      - name: Build Fuzzer
        run: AFL_HARDEN=1 ./afl-gcc -fsanitize=address ReadFile/imgRead_Fuzzer.c -o ReadFile/imgRead_Fuzzer
          
          
      - name: AFL Processing Image
        run: |
          cd ReadFile/input
          xxd image.img
          cd ..
           
      - name: AFL Run
        uses: google/oss-fuzz/infra/cifuzz/actions/run_fuzzers@master
        with:
          language: c
          
      - name: Run Fuzzer
        run: |
          afl-fuzz -i ReadFile/input/ -o ReadFile/output -m none -- ./ReadFile/imgRead_Fuzzer @@
        
       
         
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.0
        with:
           # Artifact name
          name: output
          path: ReadFile/output
